"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Plus, UsersRound } from "lucide-react";

type Community = { slug: string; name: string; description: string | null; image: string | null; category: string | null; membersCount: number; members: { status: string }[] };
export default function CommunitiesPage() {
  const [communities, setCommunities] = useState<Community[]>([]);
  useEffect(() => { void fetch("/api/communities").then((response) => response.json()).then((data: { communities?: Community[] }) => setCommunities(data.communities ?? [])); }, []);
  return <div className="mx-auto max-w-6xl"><div className="flex items-end justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.22em] text-[var(--signal)]">Shared frequency</p><h1 className="mt-2 font-[family-name:var(--font-display)] text-4xl">Communities</h1></div><button className="hidden rounded-2xl bg-[var(--ink)] px-4 py-3 text-sm font-bold text-white sm:inline-flex"><Plus className="mr-2 size-4" />Create space</button></div><p className="mt-3 max-w-xl text-sm leading-6 text-[var(--muted)]">Small worlds for the interests that keep drawing you back.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{communities.map((community) => <Link href={`/communities/${community.slug}`} key={community.slug} className="group rounded-[2rem] border border-white/70 bg-white/60 p-6 transition hover:-translate-y-1 hover:shadow-xl"><div className="grid size-12 place-items-center rounded-2xl bg-[var(--mist)] font-[family-name:var(--font-display)] text-xl">{community.image ? <img src={community.image} alt="" className="size-full rounded-2xl object-cover" /> : community.name.slice(0, 1)}</div><p className="mt-6 text-xs font-bold uppercase tracking-wider text-[var(--signal)]">{community.category ?? "Cirqua space"}</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-2xl">{community.name}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-[var(--muted)]">{community.description ?? "A space waiting for its first story."}</p><div className="mt-5 flex items-center justify-between text-xs text-[var(--muted)]"><span className="flex items-center gap-1"><UsersRound className="size-3.5" />{community.membersCount.toLocaleString()} members</span>{community.members[0]?.status === "JOINED" && <span className="rounded-full bg-[var(--mist)] px-2 py-1">Joined</span>}</div></Link>)}</div>{!communities.length && <div className="mt-8 rounded-[2rem] bg-white/50 p-12 text-center text-[var(--muted)]">Discover spaces as your community grows.</div>}</div>;
}
