"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useSession } from "next-auth/react";
import { Phone, Video } from "lucide-react";
import { useSocket } from "@/hooks/use-socket";
import { MessageBubble, type ChatMessage } from "./message-bubble";
import { MessageComposer } from "./message-composer";
import { TypingIndicator } from "./typing-indicator";

type Conversation = { id: string; title: string | null; type: string; members: { userId: string; user: { id: string; name: string | null; displayName: string | null; handle: string | null; image: string | null; presence: string } }[] };
export function ChatThread({ conversationId }: { conversationId: string }) {
  const { data: session } = useSession(); const currentUserId = session?.user?.id;
  const { socket } = useSocket(); const [conversation, setConversation] = useState<Conversation | null>(null); const [messages, setMessages] = useState<ChatMessage[]>([]); const [typingUser, setTypingUser] = useState<string | null>(null); const [reply, setReply] = useState<ChatMessage | null>(null); const bottom = useRef<HTMLDivElement>(null);
  useEffect(() => { void Promise.all([fetch(`/api/conversations/${conversationId}`).then((response) => response.json()), fetch(`/api/conversations/${conversationId}/messages`).then((response) => response.json())]).then(([thread, history]) => { setConversation(thread.conversation ?? null); setMessages(history.messages ?? []); socket?.emit("message:seen", { conversationId }); }); }, [conversationId, socket]);
  useEffect(() => { const append = (message: ChatMessage) => { if (message.conversationId === conversationId) setMessages((old) => old.some((item) => item.id === message.id) ? old : [...old, message]); }; const update = (message: ChatMessage) => setMessages((old) => old.map((item) => item.id === message.id ? message : item)); const removed = ({ messageId }: { messageId: string }) => setMessages((old) => old.filter((item) => item.id !== messageId)); const type = ({ conversationId: id, userId }: { conversationId: string; userId: string }) => { if (id === conversationId && userId !== currentUserId) setTypingUser(userId); }; const stop = ({ conversationId: id }: { conversationId: string }) => { if (id === conversationId) setTypingUser(null); }; socket?.on("message:new", append); socket?.on("message:updated", update); socket?.on("message:deleted", removed); socket?.on("typing:start", type); socket?.on("typing:stop", stop); return () => { socket?.off("message:new", append); socket?.off("message:updated", update); socket?.off("message:deleted", removed); socket?.off("typing:start", type); socket?.off("typing:stop", stop); }; }, [conversationId, currentUserId, socket]);
  useEffect(() => bottom.current?.scrollIntoView({ behavior: "smooth" }), [messages, typingUser]);
  const peer = useMemo(() => conversation?.members.find((member) => member.userId !== currentUserId)?.user, [conversation, currentUserId]);
  async function send(body: string, mediaUrl?: string, audio?: Blob) { const input = { type: audio ? "AUDIO" : mediaUrl ? "IMAGE" : "TEXT", body: body || (audio ? "Voice note" : ""), mediaUrl: audio ? URL.createObjectURL(audio) : mediaUrl, replyToId: reply?.id }; const response = await fetch(`/api/conversations/${conversationId}/messages`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); const payload = await response.json(); if (payload.message) setMessages((old) => [...old, payload.message]); setReply(null); }
  function typing(active: boolean) { socket?.emit(active ? "typing:start" : "typing:stop", { conversationId }); }
  function invite(type: "AUDIO" | "VIDEO") { if (peer) socket?.emit("call:invite", { conversationId, calleeIds: [peer.id], type }, (result: { ok: boolean; data?: unknown }) => { if (result.ok && result.data) window.dispatchEvent(new CustomEvent("cirqua:call-start", { detail: result.data })); }); }
  async function edit(message: ChatMessage) { const body = window.prompt("Edit your message", message.body); if (!body?.trim()) return; const payload = await fetch(`/api/messages/${message.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ body }) }).then((response) => response.json()); if (payload.message) setMessages((old) => old.map((item) => item.id === message.id ? payload.message : item)); }
  if (!conversation) return <div className="grid flex-1 place-items-center text-sm text-[var(--muted)]">Opening your circle…</div>;
  const name = conversation.title ?? peer?.displayName ?? peer?.name ?? peer?.handle ?? "Conversation";
  return <section className="flex min-h-[560px] flex-1 flex-col bg-[radial-gradient(circle_at_80%_0%,color-mix(in_srgb,var(--ember)_22%,transparent),transparent_34%),transparent]"><header className="flex items-center justify-between border-b border-[var(--mist)] bg-white/45 px-5 py-4 backdrop-blur"><div><h2 className="font-[family-name:var(--font-display)] text-xl">{name}</h2><p className="text-xs text-[var(--muted)]">{peer?.presence === "ONLINE" ? "In your orbit now" : "Private conversation"}</p></div><div className="flex gap-2"><button onClick={() => invite("AUDIO")} className="rounded-xl bg-white p-2.5 shadow-sm"><Phone className="size-4" /></button><button onClick={() => invite("VIDEO")} className="rounded-xl bg-white p-2.5 shadow-sm"><Video className="size-4" /></button></div></header><div className="flex-1 space-y-5 overflow-y-auto px-5 py-6">{messages.map((message) => <MessageBubble key={message.id} message={message} mine={message.senderId === currentUserId} onReply={() => setReply(message)} onReact={(emoji) => void fetch(`/api/messages/${message.id}/react`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ emoji }) })} onEdit={() => void edit(message)} onDelete={() => void fetch(`/api/messages/${message.id}?forEveryone=${message.senderId === currentUserId}`, { method: "DELETE" })} />)}{typingUser && <TypingIndicator name={peer?.name ?? peer?.handle ?? undefined} />}<div ref={bottom} /></div><MessageComposer onSend={send} onTyping={typing} reply={reply?.body} onCancelReply={() => setReply(null)} /></section>;
}
