"use client";

import Link from "next/link";
import { Archive, BellOff, Pin, Search } from "lucide-react";

export type ConversationRow = { conversationId: string; conversation: { id: string; type: string; title: string | null; image: string | null; members: { userId: string; user: { name: string | null; displayName: string | null; handle: string | null; image: string | null; presence: string } }[]; messages: { body: string; createdAt: string }[] }; unreadCount: number; isPinned: boolean; isMuted: boolean; isArchived: boolean };
export function conversationName(row: ConversationRow, currentUserId?: string) { const other = row.conversation.members.find((member) => member.userId !== currentUserId); return row.conversation.title ?? other?.user.displayName ?? other?.user.name ?? other?.user.handle ?? "Untitled conversation"; }
export function ConversationList({ conversations, activeId, query, onQuery, currentUserId }: { conversations: ConversationRow[]; activeId?: string; query: string; onQuery: (query: string) => void; currentUserId?: string }) {
  const rows = conversations.filter((row) => conversationName(row, currentUserId).toLowerCase().includes(query.toLowerCase()));
  return <aside className="flex h-full min-h-[560px] w-full flex-col border-r border-[var(--mist)] bg-white/35 md:max-w-[22rem]"><div className="p-5"><p className="text-[11px] font-bold uppercase tracking-[.22em] text-[var(--signal)]">Private circle</p><h1 className="mt-1 font-[family-name:var(--font-display)] text-3xl">Messages</h1><label className="mt-5 flex items-center gap-2 rounded-2xl bg-white px-3 py-2 text-[var(--muted)] shadow-sm"><Search className="size-4" /><input value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Find a conversation" className="w-full bg-transparent text-sm outline-none" /></label></div><div className="flex-1 space-y-1 overflow-y-auto px-2 pb-4">{rows.map((row) => { const member = row.conversation.members.find((item) => item.user.presence === "ONLINE")?.user; const latest = row.conversation.messages[0]; return <Link key={row.conversationId} href={`/messages/${row.conversation.id}`} className={`block rounded-2xl p-3 transition ${activeId === row.conversation.id ? "bg-[var(--ink)] text-white shadow-lg" : "hover:bg-white/70"}`}><div className="flex gap-3"><div className="relative grid size-11 shrink-0 place-items-center rounded-2xl bg-[var(--mist)] font-[family-name:var(--font-display)]">{row.conversation.image ? <img src={row.conversation.image} alt="" className="size-full rounded-2xl object-cover" /> : conversationName(row, currentUserId).slice(0, 1)}{member && <span className="absolute -bottom-0.5 -right-0.5 size-3 rounded-full border-2 border-white bg-[var(--signal)]" />}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-1"><p className="truncate text-sm font-bold">{conversationName(row, currentUserId)}</p>{row.isPinned && <Pin className="size-3 opacity-60" />}{row.isMuted && <BellOff className="size-3 opacity-60" />}{row.isArchived && <Archive className="size-3 opacity-60" />}</div><p className="mt-1 truncate text-xs opacity-60">{latest?.body || "No messages yet"}</p></div>{row.unreadCount > 0 && <span className="grid size-5 place-items-center rounded-full bg-[var(--signal)] text-[10px] font-bold text-white">{row.unreadCount}</span>}</div></Link>; })}{!rows.length && <p className="px-4 py-10 text-center text-sm text-[var(--muted)]">Your circle is quiet for now.</p>}</div></aside>;
}
