"use client";
import { useEffect, useState } from "react";

type Audience = "EVERYONE" | "FOLLOWERS" | "FOLLOWING" | "MUTUAL" | "NOBODY";
type Privacy = Record<"whoCanFollow" | "whoCanMessage" | "whoCanCall" | "whoCanComment" | "whoCanMention" | "whoCanTag" | "whoCanSeeStories" | "whoCanSeeActivity" | "whoCanSeeOnline", Audience> & { showReadReceipts: boolean; showTyping: boolean };
const labels: Record<keyof Privacy, string> = { whoCanFollow: "Who can follow me", whoCanMessage: "Who can message me", whoCanCall: "Who can call me", whoCanComment: "Who can comment", whoCanMention: "Who can mention me", whoCanTag: "Who can tag me", whoCanSeeStories: "Who can see my stories", whoCanSeeActivity: "Who can see my activity", whoCanSeeOnline: "Who can see my online status", showReadReceipts: "Send read receipts", showTyping: "Show when I’m typing" };
const audiences: Audience[] = ["EVERYONE", "FOLLOWERS", "FOLLOWING", "MUTUAL", "NOBODY"];
export default function PrivacySettingsPage() {
  const [privacy, setPrivacy] = useState<Privacy | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { void fetch("/api/privacy").then((response) => response.json()).then((data: { privacy?: Privacy }) => setPrivacy(data.privacy ?? null)); }, []);
  async function update(patch: Partial<Privacy>) { if (!privacy) return; const next = { ...privacy, ...patch }; setPrivacy(next); setSaving(true); await fetch("/api/privacy", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(patch) }); setSaving(false); }
  if (!privacy) return <div className="p-10 text-center text-[var(--muted)]">Loading your boundaries…</div>;
  return <div className="mx-auto max-w-2xl"><p className="text-[11px] font-bold uppercase tracking-[.22em] text-[var(--signal)]">Control room</p><h1 className="mt-2 font-[family-name:var(--font-display)] text-4xl">Privacy, on your terms</h1><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Choose the perimeter around your presence. Changes save as you make them.</p><section className="mt-8 overflow-hidden rounded-[2rem] border border-white/70 bg-white/60">{(Object.keys(labels) as (keyof Privacy)[]).map((key) => <div key={key} className="flex items-center justify-between gap-4 border-b border-[var(--mist)] p-5 last:border-0"><label className="text-sm font-medium">{labels[key]}</label>{typeof privacy[key] === "boolean" ? <button onClick={() => void update({ [key]: !privacy[key] } as Partial<Privacy>)} className={`h-7 w-12 rounded-full p-1 transition ${privacy[key] ? "bg-[var(--signal)]" : "bg-[var(--mist)]"}`}><span className={`block size-5 rounded-full bg-white transition ${privacy[key] ? "translate-x-5" : ""}`} /></button> : <select value={privacy[key] as Audience} onChange={(event) => void update({ [key]: event.target.value as Audience } as Partial<Privacy>)} className="rounded-xl bg-[var(--mist)] px-3 py-2 text-xs font-bold outline-none">{audiences.map((audience) => <option key={audience}>{audience[0] + audience.slice(1).toLowerCase()}</option>)}</select>}</div>)}</section><p className="mt-4 text-xs text-[var(--muted)]">{saving ? "Saving boundaries…" : "All changes are saved."}</p></div>;
}
